<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Echeancier extends \App\Entity\Echeancier implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Echeancier' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Echeancier' . "\0" . 'nbrEcheanciers', '' . "\0" . 'App\\Entity\\Echeancier' . "\0" . 'premierE', '' . "\0" . 'App\\Entity\\Echeancier' . "\0" . 'deuxiemeE', '' . "\0" . 'App\\Entity\\Echeancier' . "\0" . 'troisiemeE', '' . "\0" . 'App\\Entity\\Echeancier' . "\0" . 'quatriemeE', '' . "\0" . 'App\\Entity\\Echeancier' . "\0" . 'cinquiemeE', '' . "\0" . 'App\\Entity\\Echeancier' . "\0" . 'sixiemeE', '' . "\0" . 'App\\Entity\\Echeancier' . "\0" . 'septiemeE', '' . "\0" . 'App\\Entity\\Echeancier' . "\0" . 'huitiemeE', '' . "\0" . 'App\\Entity\\Echeancier' . "\0" . 'neuviemeE', '' . "\0" . 'App\\Entity\\Echeancier' . "\0" . 'dixiemeE', '' . "\0" . 'App\\Entity\\Echeancier' . "\0" . 'onziemeE', '' . "\0" . 'App\\Entity\\Echeancier' . "\0" . 'douziemeE', '' . "\0" . 'App\\Entity\\Echeancier' . "\0" . 'premierMont', '' . "\0" . 'App\\Entity\\Echeancier' . "\0" . 'deuxiemeMont', '' . "\0" . 'App\\Entity\\Echeancier' . "\0" . 'troisiemeMont', '' . "\0" . 'App\\Entity\\Echeancier' . "\0" . 'quatriemeMont', '' . "\0" . 'App\\Entity\\Echeancier' . "\0" . 'cinquiemeMont', '' . "\0" . 'App\\Entity\\Echeancier' . "\0" . 'sixiemeMont', '' . "\0" . 'App\\Entity\\Echeancier' . "\0" . 'septiemeMont', '' . "\0" . 'App\\Entity\\Echeancier' . "\0" . 'huitiemeMont', '' . "\0" . 'App\\Entity\\Echeancier' . "\0" . 'neuviemeMont', '' . "\0" . 'App\\Entity\\Echeancier' . "\0" . 'dixiemeMont', '' . "\0" . 'App\\Entity\\Echeancier' . "\0" . 'onziemeMont', '' . "\0" . 'App\\Entity\\Echeancier' . "\0" . 'douziemeMont'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Echeancier' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Echeancier' . "\0" . 'nbrEcheanciers', '' . "\0" . 'App\\Entity\\Echeancier' . "\0" . 'premierE', '' . "\0" . 'App\\Entity\\Echeancier' . "\0" . 'deuxiemeE', '' . "\0" . 'App\\Entity\\Echeancier' . "\0" . 'troisiemeE', '' . "\0" . 'App\\Entity\\Echeancier' . "\0" . 'quatriemeE', '' . "\0" . 'App\\Entity\\Echeancier' . "\0" . 'cinquiemeE', '' . "\0" . 'App\\Entity\\Echeancier' . "\0" . 'sixiemeE', '' . "\0" . 'App\\Entity\\Echeancier' . "\0" . 'septiemeE', '' . "\0" . 'App\\Entity\\Echeancier' . "\0" . 'huitiemeE', '' . "\0" . 'App\\Entity\\Echeancier' . "\0" . 'neuviemeE', '' . "\0" . 'App\\Entity\\Echeancier' . "\0" . 'dixiemeE', '' . "\0" . 'App\\Entity\\Echeancier' . "\0" . 'onziemeE', '' . "\0" . 'App\\Entity\\Echeancier' . "\0" . 'douziemeE', '' . "\0" . 'App\\Entity\\Echeancier' . "\0" . 'premierMont', '' . "\0" . 'App\\Entity\\Echeancier' . "\0" . 'deuxiemeMont', '' . "\0" . 'App\\Entity\\Echeancier' . "\0" . 'troisiemeMont', '' . "\0" . 'App\\Entity\\Echeancier' . "\0" . 'quatriemeMont', '' . "\0" . 'App\\Entity\\Echeancier' . "\0" . 'cinquiemeMont', '' . "\0" . 'App\\Entity\\Echeancier' . "\0" . 'sixiemeMont', '' . "\0" . 'App\\Entity\\Echeancier' . "\0" . 'septiemeMont', '' . "\0" . 'App\\Entity\\Echeancier' . "\0" . 'huitiemeMont', '' . "\0" . 'App\\Entity\\Echeancier' . "\0" . 'neuviemeMont', '' . "\0" . 'App\\Entity\\Echeancier' . "\0" . 'dixiemeMont', '' . "\0" . 'App\\Entity\\Echeancier' . "\0" . 'onziemeMont', '' . "\0" . 'App\\Entity\\Echeancier' . "\0" . 'douziemeMont'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Echeancier $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNbrEcheanciers(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbrEcheanciers', []);

        return parent::getNbrEcheanciers();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbrEcheanciers(int $nbrEcheanciers): \App\Entity\Echeancier
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbrEcheanciers', [$nbrEcheanciers]);

        return parent::setNbrEcheanciers($nbrEcheanciers);
    }

    /**
     * {@inheritDoc}
     */
    public function getPremierE(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPremierE', []);

        return parent::getPremierE();
    }

    /**
     * {@inheritDoc}
     */
    public function setPremierE(?\DateTimeInterface $premierE): \App\Entity\Echeancier
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPremierE', [$premierE]);

        return parent::setPremierE($premierE);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeuxiemeE(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeuxiemeE', []);

        return parent::getDeuxiemeE();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeuxiemeE(?\DateTimeInterface $deuxiemeE): \App\Entity\Echeancier
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeuxiemeE', [$deuxiemeE]);

        return parent::setDeuxiemeE($deuxiemeE);
    }

    /**
     * {@inheritDoc}
     */
    public function getTroisiemeE(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTroisiemeE', []);

        return parent::getTroisiemeE();
    }

    /**
     * {@inheritDoc}
     */
    public function setTroisiemeE(?\DateTimeInterface $troisiemeE): \App\Entity\Echeancier
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTroisiemeE', [$troisiemeE]);

        return parent::setTroisiemeE($troisiemeE);
    }

    /**
     * {@inheritDoc}
     */
    public function getQuatriemeE(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQuatriemeE', []);

        return parent::getQuatriemeE();
    }

    /**
     * {@inheritDoc}
     */
    public function setQuatriemeE(?\DateTimeInterface $quatriemeE): \App\Entity\Echeancier
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQuatriemeE', [$quatriemeE]);

        return parent::setQuatriemeE($quatriemeE);
    }

    /**
     * {@inheritDoc}
     */
    public function getCinquiemeE(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCinquiemeE', []);

        return parent::getCinquiemeE();
    }

    /**
     * {@inheritDoc}
     */
    public function setCinquiemeE(?\DateTimeInterface $cinquiemeE): \App\Entity\Echeancier
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCinquiemeE', [$cinquiemeE]);

        return parent::setCinquiemeE($cinquiemeE);
    }

    /**
     * {@inheritDoc}
     */
    public function getSixiemeE(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSixiemeE', []);

        return parent::getSixiemeE();
    }

    /**
     * {@inheritDoc}
     */
    public function setSixiemeE(?\DateTimeInterface $sixiemeE): \App\Entity\Echeancier
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSixiemeE', [$sixiemeE]);

        return parent::setSixiemeE($sixiemeE);
    }

    /**
     * {@inheritDoc}
     */
    public function getSeptiemeE(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSeptiemeE', []);

        return parent::getSeptiemeE();
    }

    /**
     * {@inheritDoc}
     */
    public function setSeptiemeE(?\DateTimeInterface $septiemeE): \App\Entity\Echeancier
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSeptiemeE', [$septiemeE]);

        return parent::setSeptiemeE($septiemeE);
    }

    /**
     * {@inheritDoc}
     */
    public function getHuitiemeE(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHuitiemeE', []);

        return parent::getHuitiemeE();
    }

    /**
     * {@inheritDoc}
     */
    public function setHuitiemeE(?\DateTimeInterface $huitiemeE): \App\Entity\Echeancier
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHuitiemeE', [$huitiemeE]);

        return parent::setHuitiemeE($huitiemeE);
    }

    /**
     * {@inheritDoc}
     */
    public function getNeuviemeE(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNeuviemeE', []);

        return parent::getNeuviemeE();
    }

    /**
     * {@inheritDoc}
     */
    public function setNeuviemeE(?\DateTimeInterface $neuviemeE): \App\Entity\Echeancier
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNeuviemeE', [$neuviemeE]);

        return parent::setNeuviemeE($neuviemeE);
    }

    /**
     * {@inheritDoc}
     */
    public function getDixiemeE(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDixiemeE', []);

        return parent::getDixiemeE();
    }

    /**
     * {@inheritDoc}
     */
    public function setDixiemeE(?\DateTimeInterface $dixiemeE): \App\Entity\Echeancier
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDixiemeE', [$dixiemeE]);

        return parent::setDixiemeE($dixiemeE);
    }

    /**
     * {@inheritDoc}
     */
    public function getOnziemeE(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOnziemeE', []);

        return parent::getOnziemeE();
    }

    /**
     * {@inheritDoc}
     */
    public function setOnziemeE(?\DateTimeInterface $onziemeE): \App\Entity\Echeancier
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOnziemeE', [$onziemeE]);

        return parent::setOnziemeE($onziemeE);
    }

    /**
     * {@inheritDoc}
     */
    public function getDouziemeE(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDouziemeE', []);

        return parent::getDouziemeE();
    }

    /**
     * {@inheritDoc}
     */
    public function setDouziemeE(?\DateTimeInterface $douziemeE): \App\Entity\Echeancier
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDouziemeE', [$douziemeE]);

        return parent::setDouziemeE($douziemeE);
    }

    /**
     * {@inheritDoc}
     */
    public function getPremierMont(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPremierMont', []);

        return parent::getPremierMont();
    }

    /**
     * {@inheritDoc}
     */
    public function setPremierMont(string $premierMont): \App\Entity\Echeancier
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPremierMont', [$premierMont]);

        return parent::setPremierMont($premierMont);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeuxiemeMont(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeuxiemeMont', []);

        return parent::getDeuxiemeMont();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeuxiemeMont(?string $deuxiemeMont): \App\Entity\Echeancier
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeuxiemeMont', [$deuxiemeMont]);

        return parent::setDeuxiemeMont($deuxiemeMont);
    }

    /**
     * {@inheritDoc}
     */
    public function getTroisiemeMont(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTroisiemeMont', []);

        return parent::getTroisiemeMont();
    }

    /**
     * {@inheritDoc}
     */
    public function setTroisiemeMont(?string $troisiemeMont): \App\Entity\Echeancier
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTroisiemeMont', [$troisiemeMont]);

        return parent::setTroisiemeMont($troisiemeMont);
    }

    /**
     * {@inheritDoc}
     */
    public function getQuatriemeMont(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQuatriemeMont', []);

        return parent::getQuatriemeMont();
    }

    /**
     * {@inheritDoc}
     */
    public function setQuatriemeMont(?string $quatriemeMont): \App\Entity\Echeancier
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQuatriemeMont', [$quatriemeMont]);

        return parent::setQuatriemeMont($quatriemeMont);
    }

    /**
     * {@inheritDoc}
     */
    public function getCinquiemeMont(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCinquiemeMont', []);

        return parent::getCinquiemeMont();
    }

    /**
     * {@inheritDoc}
     */
    public function setCinquiemeMont(?int $cinquiemeMont): \App\Entity\Echeancier
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCinquiemeMont', [$cinquiemeMont]);

        return parent::setCinquiemeMont($cinquiemeMont);
    }

    /**
     * {@inheritDoc}
     */
    public function getSixiemeMont(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSixiemeMont', []);

        return parent::getSixiemeMont();
    }

    /**
     * {@inheritDoc}
     */
    public function setSixiemeMont(?string $sixiemeMont): \App\Entity\Echeancier
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSixiemeMont', [$sixiemeMont]);

        return parent::setSixiemeMont($sixiemeMont);
    }

    /**
     * {@inheritDoc}
     */
    public function getSeptiemeMont(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSeptiemeMont', []);

        return parent::getSeptiemeMont();
    }

    /**
     * {@inheritDoc}
     */
    public function setSeptiemeMont(?string $septiemeMont): \App\Entity\Echeancier
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSeptiemeMont', [$septiemeMont]);

        return parent::setSeptiemeMont($septiemeMont);
    }

    /**
     * {@inheritDoc}
     */
    public function getHuitiemeMont(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHuitiemeMont', []);

        return parent::getHuitiemeMont();
    }

    /**
     * {@inheritDoc}
     */
    public function setHuitiemeMont(?string $huitiemeMont): \App\Entity\Echeancier
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHuitiemeMont', [$huitiemeMont]);

        return parent::setHuitiemeMont($huitiemeMont);
    }

    /**
     * {@inheritDoc}
     */
    public function getNeuviemeMont(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNeuviemeMont', []);

        return parent::getNeuviemeMont();
    }

    /**
     * {@inheritDoc}
     */
    public function setNeuviemeMont(?string $neuviemeMont): \App\Entity\Echeancier
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNeuviemeMont', [$neuviemeMont]);

        return parent::setNeuviemeMont($neuviemeMont);
    }

    /**
     * {@inheritDoc}
     */
    public function getDixiemeMont(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDixiemeMont', []);

        return parent::getDixiemeMont();
    }

    /**
     * {@inheritDoc}
     */
    public function setDixiemeMont(?string $dixiemeMont): \App\Entity\Echeancier
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDixiemeMont', [$dixiemeMont]);

        return parent::setDixiemeMont($dixiemeMont);
    }

    /**
     * {@inheritDoc}
     */
    public function getOnziemeMont(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOnziemeMont', []);

        return parent::getOnziemeMont();
    }

    /**
     * {@inheritDoc}
     */
    public function setOnziemeMont(?string $onziemeMont): \App\Entity\Echeancier
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOnziemeMont', [$onziemeMont]);

        return parent::setOnziemeMont($onziemeMont);
    }

    /**
     * {@inheritDoc}
     */
    public function getDouziemeMont(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDouziemeMont', []);

        return parent::getDouziemeMont();
    }

    /**
     * {@inheritDoc}
     */
    public function setDouziemeMont(?string $douziemeMont): \App\Entity\Echeancier
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDouziemeMont', [$douziemeMont]);

        return parent::setDouziemeMont($douziemeMont);
    }

}
