<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Facture extends \App\Entity\Facture implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Facture' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Facture' . "\0" . 'numFacture', '' . "\0" . 'App\\Entity\\Facture' . "\0" . 'reference', '' . "\0" . 'App\\Entity\\Facture' . "\0" . 'acompte', '' . "\0" . 'App\\Entity\\Facture' . "\0" . 'montAVerser', '' . "\0" . 'App\\Entity\\Facture' . "\0" . 'montVerse', '' . "\0" . 'App\\Entity\\Facture' . "\0" . 'resteAPayer', '' . "\0" . 'App\\Entity\\Facture' . "\0" . 'commandes', '' . "\0" . 'App\\Entity\\Facture' . "\0" . 'contrat'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Facture' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Facture' . "\0" . 'numFacture', '' . "\0" . 'App\\Entity\\Facture' . "\0" . 'reference', '' . "\0" . 'App\\Entity\\Facture' . "\0" . 'acompte', '' . "\0" . 'App\\Entity\\Facture' . "\0" . 'montAVerser', '' . "\0" . 'App\\Entity\\Facture' . "\0" . 'montVerse', '' . "\0" . 'App\\Entity\\Facture' . "\0" . 'resteAPayer', '' . "\0" . 'App\\Entity\\Facture' . "\0" . 'commandes', '' . "\0" . 'App\\Entity\\Facture' . "\0" . 'contrat'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Facture $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNumFacture(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumFacture', []);

        return parent::getNumFacture();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumFacture(string $numFacture): \App\Entity\Facture
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumFacture', [$numFacture]);

        return parent::setNumFacture($numFacture);
    }

    /**
     * {@inheritDoc}
     */
    public function getReference(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReference', []);

        return parent::getReference();
    }

    /**
     * {@inheritDoc}
     */
    public function setReference(string $reference): \App\Entity\Facture
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReference', [$reference]);

        return parent::setReference($reference);
    }

    /**
     * {@inheritDoc}
     */
    public function getAcompte()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAcompte', []);

        return parent::getAcompte();
    }

    /**
     * {@inheritDoc}
     */
    public function setAcompte($acompte)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAcompte', [$acompte]);

        return parent::setAcompte($acompte);
    }

    /**
     * {@inheritDoc}
     */
    public function getMontAVerser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMontAVerser', []);

        return parent::getMontAVerser();
    }

    /**
     * {@inheritDoc}
     */
    public function setMontAVerser($montAVerser)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMontAVerser', [$montAVerser]);

        return parent::setMontAVerser($montAVerser);
    }

    /**
     * {@inheritDoc}
     */
    public function getMontVerse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMontVerse', []);

        return parent::getMontVerse();
    }

    /**
     * {@inheritDoc}
     */
    public function setMontVerse($montVerse)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMontVerse', [$montVerse]);

        return parent::setMontVerse($montVerse);
    }

    /**
     * {@inheritDoc}
     */
    public function getResteAPayer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResteAPayer', []);

        return parent::getResteAPayer();
    }

    /**
     * {@inheritDoc}
     */
    public function setResteAPayer($resteAPayer)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setResteAPayer', [$resteAPayer]);

        return parent::setResteAPayer($resteAPayer);
    }

    /**
     * {@inheritDoc}
     */
    public function getCommandes(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCommandes', []);

        return parent::getCommandes();
    }

    /**
     * {@inheritDoc}
     */
    public function addCommande(\App\Entity\Commande $commande): \App\Entity\Facture
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCommande', [$commande]);

        return parent::addCommande($commande);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCommande(\App\Entity\Commande $commande): \App\Entity\Facture
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCommande', [$commande]);

        return parent::removeCommande($commande);
    }

    /**
     * {@inheritDoc}
     */
    public function getContrat(): ?\App\Entity\Contrat
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContrat', []);

        return parent::getContrat();
    }

    /**
     * {@inheritDoc}
     */
    public function setContrat(?\App\Entity\Contrat $contrat): \App\Entity\Facture
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContrat', [$contrat]);

        return parent::setContrat($contrat);
    }

}
